import "dotenv/config";
import { PrismaClient, ProfileCategory, ProfileStatus } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// Inline SVG placeholders so the seed script never depends on files that
// live under the gitignored public/uploads directory.
function placeholderImage(label: string, bg: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="100%" height="100%" fill="${bg}"/><text x="50%" y="50%" font-family="sans-serif" font-size="36" fill="#ffffff" text-anchor="middle" dominant-baseline="middle">${label}</text></svg>`;
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
}

async function main() {
  const adminEmail = process.env.SEED_ADMIN_EMAIL || "admin@example.com";
  const adminPassword = process.env.SEED_ADMIN_PASSWORD || "ChangeMe123!";
  const adminName = process.env.SEED_ADMIN_NAME || "Admin";

  const passwordHash = await bcrypt.hash(adminPassword, 12);

  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      name: adminName,
      email: adminEmail,
      passwordHash,
      role: "ADMIN",
    },
  });
  console.log(`Admin user ready: ${admin.email}`);

  await prisma.siteSetting.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      siteName: "Portfolio CMS",
      tagline: "Representing the best of the best.",
      primaryColor: "#7c3aed",
      contactEmail: adminEmail,
    },
  });
  console.log("Site settings ready.");

  const existingProfile = await prisma.profile.findUnique({ where: { slug: "ava-sterling" } });
  if (!existingProfile) {
    const profile = await prisma.profile.create({
      data: {
        slug: "ava-sterling",
        fullName: "Ava Sterling",
        stageName: "Ava Sterling",
        category: ProfileCategory.MUSICIAN,
        status: ProfileStatus.PUBLISHED,
        featured: true,
        shortBio: "Award-winning singer-songwriter blending pop and soul.",
        bio: "Ava Sterling is a singer-songwriter known for genre-blending records and electrifying live performances. This is placeholder sample content generated by the CMS seed script — replace it with real client data from the admin dashboard.",
        location: "Los Angeles, CA",
        website: "https://example.com",
        manager: { connect: { id: admin.id } },
        socialLinks: {
          create: [
            { platform: "Instagram", url: "https://instagram.com/example" },
            { platform: "YouTube", url: "https://youtube.com/example" },
          ],
        },
        portfolioItems: {
          create: [
            {
              title: "Studio Session",
              description: "Behind the scenes from the latest album recording session.",
              mediaType: "IMAGE",
              mediaUrl: placeholderImage("Studio Session", "#7c3aed"),
              category: "Music",
              featured: true,
              sortOrder: 0,
            },
            {
              title: "Live at the Grove",
              description: "Headline performance summer tour.",
              mediaType: "IMAGE",
              mediaUrl: placeholderImage("Live at the Grove", "#5b21b6"),
              category: "Live",
              sortOrder: 1,
            },
          ],
        },
        awards: {
          create: [{ title: "Breakthrough Artist of the Year", organization: "Sample Music Awards", year: 2024 }],
        },
        testimonials: {
          create: [
            {
              authorName: "Jordan Lee",
              authorRole: "Tour Promoter",
              quote: "One of the most professional and electrifying performers we've worked with.",
              rating: 5,
            },
          ],
        },
      },
    });
    console.log(`Sample profile created: ${profile.slug}`);
  } else {
    console.log("Sample profile already exists, skipping.");
  }
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
